// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Foodilizer_Group35
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Category")]
            public string Category { get; set; }

            [ColumnName(@"Sub category")]
            public string Sub_category { get; set; }

            [ColumnName(@"Category rating")]
            public float Category_rating { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"Restaurant name")]
            public string Restaurant_name { get; set; }

            [ColumnName(@"Restaurant rating")]
            public float Restaurant_rating { get; set; }

            [ColumnName(@"Veg")]
            public float Veg { get; set; }

            [ColumnName(@"Spicy level")]
            public float Spicy_level { get; set; }

            [ColumnName(@"Hot or cold")]
            public float Hot_or_cold { get; set; }

            [ColumnName(@"Organic")]
            public float Organic { get; set; }

            [ColumnName(@"Preference score")]
            public float Preference_score { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
