﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Foodilizer_Group35
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Category rating", @"Category rating"),new InputOutputColumnPair(@"Price", @"Price"),new InputOutputColumnPair(@"Quantity", @"Quantity"),new InputOutputColumnPair(@"Restaurant rating", @"Restaurant rating"),new InputOutputColumnPair(@"Veg", @"Veg"),new InputOutputColumnPair(@"Organic", @"Organic")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Category rating",@"Price",@"Quantity",@"Restaurant rating",@"Veg",@"Organic"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.LbfgsPoissonRegression(l1Regularization:20.6884225417265F,l2Regularization:0.110371741418149F,labelColumnName:@"Preference score",featureColumnName:@"Features"));

            return pipeline;
        }
    }
}
