﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Foodilizer_Group35
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Category rating", @"Category rating"),new InputOutputColumnPair(@"Price", @"Price"),new InputOutputColumnPair(@"Quantity", @"Quantity"),new InputOutputColumnPair(@"Restaurant rating", @"Restaurant rating"),new InputOutputColumnPair(@"Veg", @"Veg"),new InputOutputColumnPair(@"Spicy level", @"Spicy level"),new InputOutputColumnPair(@"Hot or cold", @"Hot or cold"),new InputOutputColumnPair(@"Organic", @"Organic")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Category rating",@"Price",@"Quantity",@"Restaurant rating",@"Veg",@"Spicy level",@"Hot or cold",@"Organic"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=33,MinimumExampleCountPerLeaf=2,NumberOfIterations=7,MaximumBinCountPerFeature=233,LearningRate=0.263518083903526F,LabelColumnName=@"Preference score",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.552099535905926F,FeatureFraction=0.76363136369957F,L1Regularization=0.215430537590396F,L2Regularization=1.44803918936309F}}));

            return pipeline;
        }
    }
}
